version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - "APP_ENV=local"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  webserver:
    image: nginx:stable-alpine
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: laravel_worker
    command: sh -c 'php artisan queue:work redis --sleep=3 --tries=3 --timeout=600'
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
      - redis
      - db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
